### ISSUE TITLE
Can't upload attachment for homework

### ISSUE THREAD

**Issue by veloii** [Classcharts-API/classcharts-api#5]
The `makeAuthedRequest` function uses undici and that doesn't support sending sending form data for the request body. This is needed to attach the file for homework. Could you add a way to retrieve the auth data and use my own fetch client? I can make the PR.

**Comment by jamesatjaminit** [comment]
Just to check, does this issue still happen now we've migrated to axios? Can you now post formdata?

**Comment by jamesatjaminit** [comment]
Closing as I believe it should be fixed now. Feel free to reopen if not
